#!/usr/bin/env bash
# Installs and configures nginx, changes the listening port to 80
# and changes the nginx landing page.

sudo apt install nginx -y
sudo rm /var/www/html/index.nginx-debian.html 
sudo echo "Hello World!" | sudo tee -a /var/www/html/index.nginx-debian.html
# Change the listening port
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
